### ISSUE TITLE
Error getting user: { message: 'Invalid Refresh Token', status: 400 }

### ISSUE THREAD

**Issue by lumenwrites** [supabase-community/auth-helpers#176] opened 2022-07-13 18:47 UTC
Hi! I'm building a Next.js app using the help of this library.

From time to time I'm seeing the following error in my logs:
```
Error getting user: { message: 'Invalid Refresh Token', status: 400 }
```

I'm relatively new to supabase, I don't really understand why this is happening. I see this error from time to time in my local development logs, and in the logs of my app deployed on Vercel.

Can you help me figure out why this is happening, and what can I do to resolve it?

**Comment by silentworks** [comment] 2022-07-15 12:39
Has this been resolved now? also, it seems this isn't related to this repo but to your general supabase setup, am I correct in assuming this?

**Comment by codewriter73** [comment] 2022-07-15 17:55
I'm also running into this error, although I'm just beginning to investigate this. For me, it can be reproduced by logging in using the basic 
```
const { error } = await supabaseClient.auth.signIn({ email, password });
```
and then leaving the page open for around an hour, and when I hot reload it throws this error. Sometimes it's fixed by hard refreshing the page, while sometimes I have to sign out and sign back in. In my UserProvider I do have autoRefreshToken set to true. I'm not doing much else other than basic database calls, so I'm not quite sure what is causing this at the moment.

**Comment by silentworks** [comment] 2022-07-16 04:00
Duplicate of #171

**Closed by silentworks** 2022-07-16 04:00 UTC
