### ISSUE TITLE
<SupaAuthHelper> is not a valid SSR component.

### ISSUE THREAD

**Issue by developerlcl** [supabase-community/auth-helpers#201] opened 2022-07-28 22:27 UTC
Just created a brand new sveltekit project and this is the first thing I added was this supabase helper module.  As I went step by step, when I got to adding code to the __layout.svelte file, this is when it errored out.

the error is: 

<SupaAuthHelper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
Error: <SupaAuthHelper> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Module.validate_component (/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/internal/index.mjs:1747:15)
    at eval (/src/routes/__layout.svelte:15:34)
    at Object.$$render (/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/internal/index.mjs:1770:22)
    at root.svelte:37:37
    at $$render (/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/internal/index.mjs:1770:22)
    at Object.render (/node_modules/.pnpm/svelte@3.49.0/node_modules/svelte/internal/index.mjs:1778:26)
    at render_response (file:///A:/Development/Sveltekit/sveltekit-supabase-auth-template/.svelte-kit/runtime/server/index.js:1461:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond_with_error (file:///A:/Development/Sveltekit/sveltekit-supabase-auth-template/.svelte-kit/runtime/server/index.js:2859:10)
    at async resolve (file:///A:/Development/Sveltekit/sveltekit-supabase-auth-template/.svelte-kit/runtime/server/index.js:3507:13)

also

Module '"@supabase/auth-helpers-sveltekit"' has no exported member 'SupaAuthHelper'.js

Any help on this would be greatly appreciated!  Thanks!

**Comment by philip-weber** [comment] 2022-07-29 05:42
I am not sure about the SSR error because I do not get those errors. Could you please provide a minimal reproduction repository (eg. on GitHub, Stackblitz, …)? That would help reproducing the error.

But to your second question, you need to import the `SupaAuthHelper` from `@supabase/auth-helpers-svelte` and not from `@supabase/auth-helpers-sveltekit`. 
Note: The package `@supabase/auth-helpers-svelte` needs to be imported separately though.

Correct:
`import { SupaAuthHelper } from '@supabase/auth-helpers-svelte';` 

Wrong:
`import { SupaAuthHelper } from '@supabase/auth-helpers-sveltekit';` 


Hope this helps a bit.

**Comment by silentworks** [comment] 2022-07-29 13:31
As @philip-weber stated above, you are importing from the wrong library. Duplicate of https://github.com/supabase-community/auth-helpers/issues/186#issuecomment-1189070970.

**Closed by silentworks** 2022-07-29 13:31 UTC
